language: generic

branches:
  only:
    - master
    - develop
    - travis

sudo: required

services:
  - docker

before_install:
  - docker pull archlinux/base

script:
  - scripts/travisDocker.sh

notifications:
  email:
    on_success: never
