name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build -t quickcurver .
    - name: Check that headless server works
      run: echo "/quit" | docker run -i quickcurver build/quickcurver -platform offscreen
    - name: Build documentation
      run: docker run quickcurver sh -c 'cd doc && doxygen'
